### ISSUE TITLE
Inheritance Support

### ISSUE THREAD

**Issue by jacobsatelbrys** [coursera/courier#1]
It says in the document that the "include" key will add all the fields but does not do inheritance. While for new projects, this is easy to get around, people looking to switch to this framework are possibly relying on inheritance in their code (at least I am)

**Comment by jpbetz** [comment]
This is a tough one. I've discussed this a couple times previously and we've decided to keep inheritance out of the schema language.  The reasoning is a bit involved, but I can summarize if needed.  

However, it sounds like what you're interested in has more to do with the generated Scala classes.  Unfortunately, we don't have any pre-existing plans to add type hierarchies to the Scala class generation. There can be multiple "includes", so  it's nontrivial to map to Scala's single inheritance... but I'll continue to think about it.

Since we can't offer you anything right now, maybe you could use pegasus unions and then convert to a type hierarchy for use in your app code? The conversion code will be a bit annoying, but pattern matching will help with it a bit.

Thanks for the feedback!

I'll leave this issue open.

**Comment by jacobsatelbrys** [comment]
Yeah, I didn’t expect it to be easy but I feel like it could be useful in a lot of cases.

I don’t know anything about pegasus but if it had a concept of generating an abstract class, that could instead be converted into a trait, and that way you can use trait inheritance. Or maybe a whole new keyword outside of pegasus would be needed. Just spouting ideas.

**Comment by jpbetz** [comment]
I've had a close look and decided that we will not support inheritance at this time. I hate to turn down early feature requests, but in this case, since neither Apache Avro, or Pegasus, the systems Courier extends, support inheritance in data bindings, and because inheritance is not directly compatible with the schema language type system, it feels like to large of a divergence from Courier's intent.

Fortunately, unions can be used for cases where type variance is needed.

I hope this isn't a deal breaker for you Jacob, your feedback has been very helpful!
