### ISSUE TITLE
Generated code legibility

### ISSUE THREAD

**Issue by eboto** [coursera/courier#8]
I love twirl, but its one down-side is legibility of the generated code due to excessive whitespace.

What do you guys think would be a good solution to this? Adding a scalariform pass is the first thing that comes to mind, but I'm not sure what your thoughts are wrt adding that dependency.

**Comment by saeta** [comment]
@eboto we've explored a number of different methods for code gen; @jpbetz has the details. Probably the best formatted code was code generated via treehugger. We opted, however, to use twirl templates, in order to optimize for courier contributions. :-)

I remember @jpbetz investigating using scalariform. Looking at the latest generated code, it looks like we already are properly formatting, so I'm going to close this as fixed, once you upgrade to the latest. Please feel free to re-open if I'm mistaken.

Thanks @eboto !!

**Comment by saeta** [comment]
See https://github.com/coursera/courier/blob/90e4e81bf3d7d0af78b334924c049c01bd27fea1/generator/src/main/scala/org/coursera/courier/ScalaGenerator.scala#L86 :-)

**Comment by jpbetz** [comment]
@eboto Yep, we've been formatting with scalariform for a bit now.  We're pretty happy with it.  I'm publishing 0.12.3 to maven central now.

We did play around with Treehugger, but Twirl is so much easier to work with when authoring and making changes.

Good news is that we found scalariform to be as good or better than Treehugger for formatting.  And if we need to improve formatting further, it will be much easier to improve scalariform to do what we need than it would be to improve Treehugger.
